version: '3'
services:
  quotes:
    image: gearpawarit/quotes:latest
    networks:
      - simple-network
  api:
    image: gearpawarit/api:latest
    environment:
      - "QUOTES_API=http://quotes:5000"
    depends_on:
      - quotes
    ports:
      - "3000:3000"
    networks:
      - simple-network
  frontend:
    image: gearpawarit/frontend:latest
    deploy:
      replicas: 2
    networks:
      - simple-network
  reverse:
    image: gearpawarit/reverse:latest
    # volumes:
    #   - ./ReverseProxy/nginx:/etc/nginx
    depends_on:
      - frontend
    ports:
      - "80:80"
    networks:
      - simple-network
    deploy:
      mode: global
networks:
  simple-network:
    driver: overlay
    